config/routes.rb
Rails.application.routes.draw do
   #get 'ueditor/demo'

  scope '/:locale' do
    resources :attachments, only: [:index, :new, :create, :destroy]
    resources :notices, only: :index
    resources :leave_words, only: [:new, :create]

    get 'dashboard' => 'home#dashboard'
    get 'personal/logs'

    get 'ueditor/api'
    post 'ueditor/api'
  end

  get 'google(*id).html', to: 'home#google', as: :google_verify
  get 'baidu_verify_(*id).html', to: 'home#baidu', as: :baidu_verify
  get 'robots', to: 'home#robots', as: :robots_txt, constraints: {format: :txt}

  Rails.application.config.magnolia['engines'].each {|e| mount Object.const_get("#{e}::Engine") => e.downcase}

  devise_for :users

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  validates :title, :content_type, :size, :resource_type, :resource_id, presence: true

  belongs_to :user

  def image?
    self.content_type.start_with? 'image'
  end

  def read!(file)
    self.content_type = file.content_type
    self.title = file.original_filename
    self.size = File.size file.tempfile
    self.avatar = file
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  layout 'dashboard'

  def index
    @attachment = Attachment.new params.permit(:resource_type, :resource_id)
    res = Object.const_get(@attachment.resource_type).find @attachment.resource_id
    authorize res, :edit?
    @attachments = Attachment.where(params.permit(:resource_type, :resource_id)).order(sort_order: :asc)
  end

  def new
    @attachment = Attachment.new params.permit(:resource_type, :resource_id)
    res = Object.const_get(@attachment.resource_type).find @attachment.resource_id
    authorize res, :edit?
    @attachment.sort_order = 0
  end

  def create
    @attachment = Attachment.new params.require(:attachment).permit(:resource_type, :resource_id, :sort_order)

    res = Object.const_get(@attachment.resource_type).find @attachment.resource_id
    authorize res, :edit?

    @attachment.user = current_user
    @attachment.read! params.require(:attachment).fetch(:file)
    puts '#'*80, @attachment.inspect
    if @attachment.save
      redirect_to attachments_path(params.require(:attachment).permit(:resource_type, :resource_id))
    else
      render 'new'
    end
  end

  def destroy
    @attachment = Attachment.find params[:id]
    res = Object.const_get(@attachment.resource_type).find @attachment.resource_id
    authorize res, :edit?
    @attachment.destroy
    redirect_to attachments_path(resource_type:@attachment.resource_type, resource_id:@attachment.resource_id)
  end
end

app/views/attachments/index.html.slim
h2
  = @title = t '.title'
  | &nbsp;
  = link_to t('buttons.upload'), new_attachment_path(params.permit(:resource_type, :resource_id)), class: 'btn btn-link'
hr
ul class="list-group"
  -@attachments.each do |i|
    li class='list-group-item'
      - if i.image?
        h5 #{i.sort_order}: #{i.title}
        = image_tag i.avatar.url
      - else
        = link_to i.title, i.avatar.url, target: :_blank
      div class="btn-group btn-group-sm"
        =render 'shared/btn-remove', url:attachment_path(i)

app/views/attachments/new.html.slim
h2 #{@title = t '.title'}
hr
= simple_form_for @attachment, html: {multipart: true} do |f|
  - if @attachment.errors.any?
    =@attachment.errors.full_messages.inspect

  = f.input :resource_id, as: :hidden
  = f.input :resource_type, as: :hidden
  = f.input :file, as: :file
  = f.input :sort_order, collection: -10..10
  = f.button :submit, t('buttons.submit')