config/routes.rb
Rails.application.routes.draw do
   #get 'ueditor/demo'

  scope '/:locale' do
    resources :attachments, only: [:index, :new, :create, :destroy]
    resources :notices, only: :index
    resources :leave_words, only: [:new, :create]

    get 'dashboard' => 'home#dashboard'
    get 'personal/logs'

    get 'ueditor/api'
    post 'ueditor/api'
  end

  get 'google(*id).html', to: 'home#google', as: :google_verify
  get 'baidu_verify_(*id).html', to: 'home#baidu', as: :baidu_verify
  get 'robots', to: 'home#robots', as: :robots_txt, constraints: {format: :txt}

  Rails.application.config.magnolia['engines'].each {|e| mount Object.const_get("#{e}::Engine") => e.downcase}

  devise_for :users

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]

  def index
    redirect_to send(Setting.home).root_path
  end

  def dashboard
    render layout: 'dashboard'
  end

  def robots

    render plain: <<EOF
# See http://www.robotstxt.org/robotstxt.html for documentation on how to use the robots.txt file
#
# To ban all spiders from the entire site uncomment the next two lines:
# User-agent: *
# Disallow: /
Sitemap: https://#{ENV['HOST']}/sitemap.xml.gz
EOF
  end

  def google
    code = Setting.google_verify_code
    if params[:id] == code
      render plain: "google-site-verification: google#{code}.html"
    else
      head :not_found
    end
  end

  def baidu
    code = Setting.baidu_verify_code
    if params[:id] == code
      render plain: code
    else
      head :not_found
    end
  end
end

app/views/home/dashboard.html.slim
- @title = t '.title'

div class="row block"
  h4 #{t '.profile'}
  hr
  div class="btn-group" role="group" aria-label="personal"
    = link_to(t('devise.registrations.edit.title'), edit_user_registration_path, {class: 'btn btn-secondary'})
    = link_to(t('personal.logs.title'), personal_logs_path, {class: 'btn btn-secondary'})

- Rails.application.config.magnolia['engines'].each do |e|
  - en = Object.const_get(e).dashboard(current_user)

  - unless en.nil?
    div class="row block"
      h4 #{t en.fetch(:label)}
      hr
      div class="btn-group" role="group" aria-label="#{e}-bar"
        - sty = 'btn-secondary'
        - en.fetch(:links).each do |l|
          - if l.nil?
            - sty = 'btn-outline-warning'
          - else
            = link_to t(l.fetch(:label)), send(e.downcase).send(l.fetch(:href)), {class: "btn #{sty}", target: (l[:blank] ? :_blank : :_parent)}